### ISSUE TITLE
Польза паттерна Builder

### ISSUE THREAD

**Issue by maked0n** [ashpool-techprog/PizzaCMS#1]
В чем смысл использования паттерна Builder для такого объекта?
https://github.com/ashpool-techprog/PizzaCMS/blob/d4d1a99af7771564bbb1049edba83f811ebacf70/include/Pizza.h#L54

**Comment by ashpooljh** [comment]
@maked0n Pizza теперь immutable. Подробности в коммит-сообщении.

**Comment by ashpooljh** [comment]
Смысл применения паттерна Builder в том, что пицца -- это сложный объект: её создание подразумевает несколько шагов, результат каждого из которых потенциально нужно контроллировать. Кроме того, изменить пиццу после её создания не представляется возможным. Пицц существует несколько видов, и для каждого из них удобно применять отдельный конкретный билдер. Всё это позволяет абстрагировать процесс создания пиццы со стороны "директора" (class Kitchen)
